- name: Configure basic dev VM
  hosts: devhosts
  become: true

  roles:
    - base
    - local-filesystem
    - nfs-client
    # - smb-client
    - docker
    - apptainer
    - role: r
      when: r_enabled | default(false)
    - role: rstudio-server
      when: rstudio_server_enabled | default(false)
