[adminhosts]
infra-admin-01 ansible_host=10.10.10.10
#infra-admin-02 ansible_host=10.10.10.11

[devhosts]
dev01 ansible_host=10.10.10.101
dev02 ansible_host=10.10.10.102
dev03 ansible_host=10.10.10.103

[dbhosts]
mongodb01 ansible_host=10.10.10.32

[fileservers]
infra-fs-01 ansible_host=10.10.10.16

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
