[devhosts]
devvm01 ansible_host=10.10.10.101
devvm02 ansible_host=10.10.10.102

[dbhosts]
mongodb01 ansible_host=10.10.10.32

[devhosts:vars]
ansible_user=jonas
ansible_python_interpreter=/usr/bin/python3
