---
# Numeric identities must match the authoritative NFS environment.
managed_groups:
  - name: cmd-bnf
    gid: 1004

managed_users:
  - name: jonas
    uid: 119
    primary_group: cmd-bnf
    primary_gid: 1004
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOLJ0ulw3GyyQFosjDpkUwqTJfLALDs7cPi/5sHahWv jonas@RS30166454"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNPlw3utaGuPGTHHFghYjoWtDe+MoLU+P3Fi3snIgMr7sYphuAcpYJrm1tHg9GHTjNXM5UqddtUvq+HjJy9odDPe9PNGxZwMDo8CsRwMBZmynozw2r8MDjZUXeglOOpNyNuN2PYNcaI1KAzRpY07rxJIQ9weMa9t+szTPc4H0Xtm0pZNMIggApUvD9JwzfiNeospHSXqnwMGHpetv2gjnFElQ5Ra/sXhM90mD8LHrHxXiwTh96cMqstZaA3rMZQAyv40N5vYtrPLh5S5sPf8SAv6FcNwHa/GgKa6q73N2ffPZbFlFLAk7Fd+zjOmDc2uBRNu3yutibJ0xZK4G7yO+F1Edt6ciC+0F77KWKD/avlJLZqDpdLSFq+QS2Ri3NCpivMJhfAoPP4HjIQG5X3KdTKUm5WXveUY7ITtTrH10fRIbRP7dGKYpVlhNOzMDzI2Xbn+by1dmEEng9GqJSx+qLJGaD3Pf2BdFYGYwB/5IqyVI4RDyyy+2G4WolV9zAmjUYeGRoEcIvHcirbU+NA2u6mfc86ulvs4BKH7N0gVxtTms3j5SKvPng3sLEuT03Ae0MGr6QGAgOU6v6wmz5BdK2vfsDBiTaJDx+bXDcv5C++0X31YGcflklCOmOB/Al7N7tLMlOrfzR01BqfDwVAxLt9585BHl63NBjHEzFSGPGNw== jonas@cloud8.se"

  - name: jakob
    uid: 1029
    primary_group: cmd-bnf
    primary_gid: 1004
    ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8Hxg9Q7FU/Qy999KNvKyc1/VXRvFn+LMMA0gnLHhdd36q07ztVtB3YzAYZRHTos37H9ANPyfmzWv7phDlNU8Xi3pH+dN2X+NkFyG/wBgdvARvBP/Qzbd2Ze9uiqO8JyNqPtsmHMSC43NzLPszHAcnyZdKbyExpNogVik3DmEn39euHes67yKpYmDVDa8OUgPkK8XuaRG8q5YAMlMu64TOjGpoKN33YTrvsQi6PnZQQFQAmMFMu+2repUSk6sArixJbKoa67E4YJcrnOs7uNCoKa5ftP8wT5JHr8U+qgM6H1Rk0RAvCkJ+dOy39rGG6boUfJEzN1DRDBhJ9YdRNtG1 jakob@MTLUCMDS1"

managed_users:
  - name: jonas
    uid: 119
    primary_group: cmd-bnf
    primary_gid: 1004

  - name: jakob
    uid: 1029
    primary_group: cmd-bnf
    primary_gid: 1004
